/*
 * Artifacts API
 *  Artifacts is an API-based MMO game where you can manage 5 characters to explore, fight, gather resources, craft items and much more.  Website: https://artifactsmmo.com/  Documentation: https://docs.artifactsmmo.com/  OpenAPI Spec: https://api.artifactsmmo.com/openapi.json 
 *
 * The version of the OpenAPI document: 3.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for CharacterLeaderboardSchema
 */
public class CharacterLeaderboardSchemaTest {
    private final CharacterLeaderboardSchema model = new CharacterLeaderboardSchema();

    /**
     * Model tests for CharacterLeaderboardSchema
     */
    @Test
    public void testCharacterLeaderboardSchema() {
        // TODO: test CharacterLeaderboardSchema
    }

    /**
     * Test the property 'position'
     */
    @Test
    public void positionTest() {
        // TODO: test position
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'account'
     */
    @Test
    public void accountTest() {
        // TODO: test account
    }

    /**
     * Test the property 'skin'
     */
    @Test
    public void skinTest() {
        // TODO: test skin
    }

    /**
     * Test the property 'level'
     */
    @Test
    public void levelTest() {
        // TODO: test level
    }

    /**
     * Test the property 'totalXp'
     */
    @Test
    public void totalXpTest() {
        // TODO: test totalXp
    }

    /**
     * Test the property 'miningLevel'
     */
    @Test
    public void miningLevelTest() {
        // TODO: test miningLevel
    }

    /**
     * Test the property 'miningTotalXp'
     */
    @Test
    public void miningTotalXpTest() {
        // TODO: test miningTotalXp
    }

    /**
     * Test the property 'woodcuttingLevel'
     */
    @Test
    public void woodcuttingLevelTest() {
        // TODO: test woodcuttingLevel
    }

    /**
     * Test the property 'woodcuttingTotalXp'
     */
    @Test
    public void woodcuttingTotalXpTest() {
        // TODO: test woodcuttingTotalXp
    }

    /**
     * Test the property 'fishingLevel'
     */
    @Test
    public void fishingLevelTest() {
        // TODO: test fishingLevel
    }

    /**
     * Test the property 'fishingTotalXp'
     */
    @Test
    public void fishingTotalXpTest() {
        // TODO: test fishingTotalXp
    }

    /**
     * Test the property 'weaponcraftingLevel'
     */
    @Test
    public void weaponcraftingLevelTest() {
        // TODO: test weaponcraftingLevel
    }

    /**
     * Test the property 'weaponcraftingTotalXp'
     */
    @Test
    public void weaponcraftingTotalXpTest() {
        // TODO: test weaponcraftingTotalXp
    }

    /**
     * Test the property 'gearcraftingLevel'
     */
    @Test
    public void gearcraftingLevelTest() {
        // TODO: test gearcraftingLevel
    }

    /**
     * Test the property 'gearcraftingTotalXp'
     */
    @Test
    public void gearcraftingTotalXpTest() {
        // TODO: test gearcraftingTotalXp
    }

    /**
     * Test the property 'jewelrycraftingLevel'
     */
    @Test
    public void jewelrycraftingLevelTest() {
        // TODO: test jewelrycraftingLevel
    }

    /**
     * Test the property 'jewelrycraftingTotalXp'
     */
    @Test
    public void jewelrycraftingTotalXpTest() {
        // TODO: test jewelrycraftingTotalXp
    }

    /**
     * Test the property 'cookingLevel'
     */
    @Test
    public void cookingLevelTest() {
        // TODO: test cookingLevel
    }

    /**
     * Test the property 'cookingTotalXp'
     */
    @Test
    public void cookingTotalXpTest() {
        // TODO: test cookingTotalXp
    }

    /**
     * Test the property 'alchemyLevel'
     */
    @Test
    public void alchemyLevelTest() {
        // TODO: test alchemyLevel
    }

    /**
     * Test the property 'alchemyTotalXp'
     */
    @Test
    public void alchemyTotalXpTest() {
        // TODO: test alchemyTotalXp
    }

    /**
     * Test the property 'gold'
     */
    @Test
    public void goldTest() {
        // TODO: test gold
    }

}
