/*
 * Artifacts API
 *  Artifacts is an API-based MMO game where you can manage 5 characters to explore, fight, gather resources, craft items and much more.  Website: https://artifactsmmo.com/  Documentation: https://docs.artifactsmmo.com/  OpenAPI Spec: https://api.artifactsmmo.com/openapi.json 
 *
 * The version of the OpenAPI document: 3.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.AccountStatus;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for MyAccountDetails
 */
public class MyAccountDetailsTest {
    private final MyAccountDetails model = new MyAccountDetails();

    /**
     * Model tests for MyAccountDetails
     */
    @Test
    public void testMyAccountDetails() {
        // TODO: test MyAccountDetails
    }

    /**
     * Test the property 'username'
     */
    @Test
    public void usernameTest() {
        // TODO: test username
    }

    /**
     * Test the property 'email'
     */
    @Test
    public void emailTest() {
        // TODO: test email
    }

    /**
     * Test the property 'subscribed'
     */
    @Test
    public void subscribedTest() {
        // TODO: test subscribed
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'badges'
     */
    @Test
    public void badgesTest() {
        // TODO: test badges
    }

    /**
     * Test the property 'gems'
     */
    @Test
    public void gemsTest() {
        // TODO: test gems
    }

    /**
     * Test the property 'achievementsPoints'
     */
    @Test
    public void achievementsPointsTest() {
        // TODO: test achievementsPoints
    }

    /**
     * Test the property 'banned'
     */
    @Test
    public void bannedTest() {
        // TODO: test banned
    }

    /**
     * Test the property 'banReason'
     */
    @Test
    public void banReasonTest() {
        // TODO: test banReason
    }

}
