/*
 * Artifacts API
 *  Artifacts is an API-based MMO game where you can manage 5 characters to explore, fight, gather resources, craft items and much more.  Website: https://artifactsmmo.com/  Documentation: https://docs.artifactsmmo.com/  OpenAPI Spec: https://api.artifactsmmo.com/openapi.json 
 *
 * The version of the OpenAPI document: 3.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.client.model.RewardsSchema;
import org.openapitools.client.model.TaskType;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for TaskFullSchema
 */
public class TaskFullSchemaTest {
    private final TaskFullSchema model = new TaskFullSchema();

    /**
     * Model tests for TaskFullSchema
     */
    @Test
    public void testTaskFullSchema() {
        // TODO: test TaskFullSchema
    }

    /**
     * Test the property 'code'
     */
    @Test
    public void codeTest() {
        // TODO: test code
    }

    /**
     * Test the property 'level'
     */
    @Test
    public void levelTest() {
        // TODO: test level
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'minQuantity'
     */
    @Test
    public void minQuantityTest() {
        // TODO: test minQuantity
    }

    /**
     * Test the property 'maxQuantity'
     */
    @Test
    public void maxQuantityTest() {
        // TODO: test maxQuantity
    }

    /**
     * Test the property 'skill'
     */
    @Test
    public void skillTest() {
        // TODO: test skill
    }

    /**
     * Test the property 'rewards'
     */
    @Test
    public void rewardsTest() {
        // TODO: test rewards
    }

}
