package hydra.model;

public enum BotEffect {
	RES_WATER, RES_EARTH, RES_FIRE, RES_AIR, DMG_WATER, DMG_EARTH, DMG_FIRE, DMG_AIR, ATTACK_WATER, ATTACK_EARTH,
	ATTACK_FIRE, ATTACK_AIR, HP, HASTE, WOODCUTTING, FISHING, MINING, RESTORE, BOOST_HP, BOOST_DMG_AIR, BOOST_DMG_WATER,
	BOOST_DMG_EARTH, BOOST_DMG_FIRE, HEAL, GOLD, ALCHEMY, INVENTORY_SPACE, BOOST_RES_WATER, BOOST_RES_FIRE,
	BOOST_RES_AIR, BOOST_RES_EARTH, TELEPORT_X, TELEPORT_Y
}
