/*
 * Artifacts API
 *  Artifacts is an API-based MMO game where you can manage 5 characters to explore, fight, gather resources, craft items and much more.  Website: https://artifactsmmo.com/  Documentation: https://docs.artifactsmmo.com/  OpenAPI Spec: https://api.artifactsmmo.com/openapi.json 
 *
 * The version of the OpenAPI document: 3.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.JsonElement;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Gets or Sets AchievementType
 */
@JsonAdapter(AchievementType.Adapter.class)
public enum AchievementType {
  
  COMBAT_KILL("combat_kill"),
  
  COMBAT_DROP("combat_drop"),
  
  COMBAT_LEVEL("combat_level"),
  
  GATHERING("gathering"),
  
  CRAFTING("crafting"),
  
  RECYCLING("recycling"),
  
  TASK("task"),
  
  OTHER("other");

  private String value;

  AchievementType(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static AchievementType fromValue(String value) {
    for (AchievementType b : AchievementType.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<AchievementType> {
    @Override
    public void write(final JsonWriter jsonWriter, final AchievementType enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public AchievementType read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return AchievementType.fromValue(value);
    }
  }

  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
    String value = jsonElement.getAsString();
    AchievementType.fromValue(value);
  }
}

