/*
 * Artifacts API
 *  Artifacts is an API-based MMO game where you can manage 5 characters to explore, fight, gather resources, craft items and much more.  Website: https://artifactsmmo.com/  Documentation: https://docs.artifactsmmo.com/  OpenAPI Spec: https://api.artifactsmmo.com/openapi.json 
 *
 * The version of the OpenAPI document: 3.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.JsonElement;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Gets or Sets ItemType
 */
@JsonAdapter(ItemType.Adapter.class)
public enum ItemType {
  
  UTILITY("utility"),
  
  BODY_ARMOR("body_armor"),
  
  WEAPON("weapon"),
  
  RESOURCE("resource"),
  
  LEG_ARMOR("leg_armor"),
  
  HELMET("helmet"),
  
  BOOTS("boots"),
  
  SHIELD("shield"),
  
  AMULET("amulet"),
  
  RING("ring"),
  
  ARTIFACT("artifact"),
  
  CURRENCY("currency"),
  
  CONSUMABLE("consumable");

  private String value;

  ItemType(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static ItemType fromValue(String value) {
    for (ItemType b : ItemType.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<ItemType> {
    @Override
    public void write(final JsonWriter jsonWriter, final ItemType enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public ItemType read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return ItemType.fromValue(value);
    }
  }

  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
    String value = jsonElement.getAsString();
    ItemType.fromValue(value);
  }
}

