/*
 * Artifacts API
 *  Artifacts is an API-based MMO game where you can manage 5 characters to explore, fight, gather resources, craft items and much more.  Website: https://artifactsmmo.com/  Documentation: https://docs.artifactsmmo.com/  OpenAPI Spec: https://api.artifactsmmo.com/openapi.json 
 *
 * The version of the OpenAPI document: 3.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.JsonElement;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Gets or Sets ItemSlot
 */
@JsonAdapter(ItemSlot.Adapter.class)
public enum ItemSlot {
  
  WEAPON("weapon"),
  
  SHIELD("shield"),
  
  HELMET("helmet"),
  
  BODY_ARMOR("body_armor"),
  
  LEG_ARMOR("leg_armor"),
  
  BOOTS("boots"),
  
  RING1("ring1"),
  
  RING2("ring2"),
  
  AMULET("amulet"),
  
  ARTIFACT1("artifact1"),
  
  ARTIFACT2("artifact2"),
  
  ARTIFACT3("artifact3"),
  
  UTILITY1("utility1"),
  
  UTILITY2("utility2");

  private String value;

  ItemSlot(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static ItemSlot fromValue(String value) {
    for (ItemSlot b : ItemSlot.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<ItemSlot> {
    @Override
    public void write(final JsonWriter jsonWriter, final ItemSlot enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public ItemSlot read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return ItemSlot.fromValue(value);
    }
  }

  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
    String value = jsonElement.getAsString();
    ItemSlot.fromValue(value);
  }
}

