/*
 * Artifacts API
 *  Artifacts is an API-based MMO game where you can manage 5 characters to explore, fight, gather resources, craft items and much more.  Website: https://artifactsmmo.com/  Documentation: https://docs.artifactsmmo.com/  OpenAPI Spec: https://api.artifactsmmo.com/openapi.json 
 *
 * The version of the OpenAPI document: 3.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.AchievementResponseSchema;
import org.openapitools.client.model.AchievementType;
import org.openapitools.client.model.DataPageAchievementSchema;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for AchievementsApi
 */
@Disabled
public class AchievementsApiTest {

    private final AchievementsApi api = new AchievementsApi();

    /**
     * Get Achievement
     *
     * Retrieve the details of a achievement.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getAchievementAchievementsCodeGetTest() throws ApiException {
        String code = null;
        AchievementResponseSchema response = api.getAchievementAchievementsCodeGet(code);
        // TODO: test validations
    }

    /**
     * Get All Achievements
     *
     * List of all achievements.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getAllAchievementsAchievementsGetTest() throws ApiException {
        AchievementType type = null;
        Integer page = null;
        Integer size = null;
        DataPageAchievementSchema response = api.getAllAchievementsAchievementsGet(type, page, size);
        // TODO: test validations
    }

}
