/*
 * Artifacts API
 *  Artifacts is an API-based MMO game where you can manage 5 characters to explore, fight, gather resources, craft items and much more.  Website: https://artifactsmmo.com/  Documentation: https://docs.artifactsmmo.com/  OpenAPI Spec: https://api.artifactsmmo.com/openapi.json 
 *
 * The version of the OpenAPI document: 3.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.BadgeResponseSchema;
import org.openapitools.client.model.DataPageBadgeSchema;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for BadgesApi
 */
@Disabled
public class BadgesApiTest {

    private final BadgesApi api = new BadgesApi();

    /**
     * Get All Badges
     *
     * List of all badges.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getAllBadgesBadgesGetTest() throws ApiException {
        Integer page = null;
        Integer size = null;
        DataPageBadgeSchema response = api.getAllBadgesBadgesGet(page, size);
        // TODO: test validations
    }

    /**
     * Get Badge
     *
     * Retrieve the details of a badge.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getBadgeBadgesCodeGetTest() throws ApiException {
        String code = null;
        BadgeResponseSchema response = api.getBadgeBadgesCodeGet(code);
        // TODO: test validations
    }

}
