/*
 * Artifacts API
 *  Artifacts is an API-based MMO game where you can manage 5 characters to explore, fight, gather resources, craft items and much more.  Website: https://artifactsmmo.com/  Documentation: https://docs.artifactsmmo.com/  OpenAPI Spec: https://api.artifactsmmo.com/openapi.json 
 *
 * The version of the OpenAPI document: 3.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.DataPageGEOrderSchema;
import org.openapitools.client.model.DataPageGeOrderHistorySchema;
import org.openapitools.client.model.GEOrderReponseSchema;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for GrandExchangeApi
 */
@Disabled
public class GrandExchangeApiTest {

    private final GrandExchangeApi api = new GrandExchangeApi();

    /**
     * Get Ge Sell History
     *
     * Fetch the sales history of the item for the last 7 days.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getGeSellHistoryGrandexchangeHistoryCodeGetTest() throws ApiException {
        String code = null;
        String seller = null;
        String buyer = null;
        Integer page = null;
        Integer size = null;
        DataPageGeOrderHistorySchema response = api.getGeSellHistoryGrandexchangeHistoryCodeGet(code, seller, buyer, page, size);
        // TODO: test validations
    }

    /**
     * Get Ge Sell Order
     *
     * Retrieve the sell order of a item.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getGeSellOrderGrandexchangeOrdersIdGetTest() throws ApiException {
        String id = null;
        GEOrderReponseSchema response = api.getGeSellOrderGrandexchangeOrdersIdGet(id);
        // TODO: test validations
    }

    /**
     * Get Ge Sell Orders
     *
     * Fetch all sell orders.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getGeSellOrdersGrandexchangeOrdersGetTest() throws ApiException {
        String code = null;
        String seller = null;
        Integer page = null;
        Integer size = null;
        DataPageGEOrderSchema response = api.getGeSellOrdersGrandexchangeOrdersGet(code, seller, page, size);
        // TODO: test validations
    }

}
