/*
 * Artifacts API
 *  Artifacts is an API-based MMO game where you can manage 5 characters to explore, fight, gather resources, craft items and much more.  Website: https://artifactsmmo.com/  Documentation: https://docs.artifactsmmo.com/  OpenAPI Spec: https://api.artifactsmmo.com/openapi.json 
 *
 * The version of the OpenAPI document: 3.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.BankResponseSchema;
import org.openapitools.client.model.ChangePassword;
import org.openapitools.client.model.DataPageGEOrderSchema;
import org.openapitools.client.model.DataPageGeOrderHistorySchema;
import org.openapitools.client.model.DataPageSimpleItemSchema;
import org.openapitools.client.model.MyAccountDetailsSchema;
import org.openapitools.client.model.ResponseSchema;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for MyAccountApi
 */
@Disabled
public class MyAccountApiTest {

    private final MyAccountApi api = new MyAccountApi();

    /**
     * Change Password
     *
     * Change your account password. Changing the password reset the account token.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void changePasswordMyChangePasswordPostTest() throws ApiException {
        ChangePassword changePassword = null;
        ResponseSchema response = api.changePasswordMyChangePasswordPost(changePassword);
        // TODO: test validations
    }

    /**
     * Get Account Details
     *
     * Fetch account details.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getAccountDetailsMyDetailsGetTest() throws ApiException {
        MyAccountDetailsSchema response = api.getAccountDetailsMyDetailsGet();
        // TODO: test validations
    }

    /**
     * Get Bank Details
     *
     * Fetch bank details.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getBankDetailsMyBankGetTest() throws ApiException {
        BankResponseSchema response = api.getBankDetailsMyBankGet();
        // TODO: test validations
    }

    /**
     * Get Bank Items
     *
     * Fetch all items in your bank.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getBankItemsMyBankItemsGetTest() throws ApiException {
        String itemCode = null;
        Integer page = null;
        Integer size = null;
        DataPageSimpleItemSchema response = api.getBankItemsMyBankItemsGet(itemCode, page, size);
        // TODO: test validations
    }

    /**
     * Get Ge Sell History
     *
     * Fetch your sales history of the last 7 days.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getGeSellHistoryMyGrandexchangeHistoryGetTest() throws ApiException {
        String id = null;
        String code = null;
        Integer page = null;
        Integer size = null;
        DataPageGeOrderHistorySchema response = api.getGeSellHistoryMyGrandexchangeHistoryGet(id, code, page, size);
        // TODO: test validations
    }

    /**
     * Get Ge Sell Orders
     *
     * Fetch your sell orders details.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getGeSellOrdersMyGrandexchangeOrdersGetTest() throws ApiException {
        String code = null;
        Integer page = null;
        Integer size = null;
        DataPageGEOrderSchema response = api.getGeSellOrdersMyGrandexchangeOrdersGet(code, page, size);
        // TODO: test validations
    }

}
