/*
 * Artifacts API
 *  Artifacts is an API-based MMO game where you can manage 5 characters to explore, fight, gather resources, craft items and much more.  Website: https://artifactsmmo.com/  Documentation: https://docs.artifactsmmo.com/  OpenAPI Spec: https://api.artifactsmmo.com/openapi.json 
 *
 * The version of the OpenAPI document: 3.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiCallback;
import org.openapitools.client.ApiClient;
import org.openapitools.client.ApiException;
import org.openapitools.client.ApiResponse;
import org.openapitools.client.Configuration;
import org.openapitools.client.Pair;
import org.openapitools.client.ProgressRequestBody;
import org.openapitools.client.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import org.openapitools.client.model.AchievementResponseSchema;
import org.openapitools.client.model.AchievementType;
import org.openapitools.client.model.DataPageAchievementSchema;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class AchievementsApi {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public AchievementsApi() {
        this(Configuration.getDefaultApiClient());
    }

    public AchievementsApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    /**
     * Build call for getAchievementAchievementsCodeGet
     * @param code The code of the achievement. (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successfully fetched achievement. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> achievement not found. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getAchievementAchievementsCodeGetCall(String code, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/achievements/{code}"
            .replace("{" + "code" + "}", localVarApiClient.escapeString(code.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getAchievementAchievementsCodeGetValidateBeforeCall(String code, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'code' is set
        if (code == null) {
            throw new ApiException("Missing the required parameter 'code' when calling getAchievementAchievementsCodeGet(Async)");
        }

        return getAchievementAchievementsCodeGetCall(code, _callback);

    }

    /**
     * Get Achievement
     * Retrieve the details of a achievement.
     * @param code The code of the achievement. (required)
     * @return AchievementResponseSchema
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successfully fetched achievement. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> achievement not found. </td><td>  -  </td></tr>
     </table>
     */
    public AchievementResponseSchema getAchievementAchievementsCodeGet(String code) throws ApiException {
        ApiResponse<AchievementResponseSchema> localVarResp = getAchievementAchievementsCodeGetWithHttpInfo(code);
        return localVarResp.getData();
    }

    /**
     * Get Achievement
     * Retrieve the details of a achievement.
     * @param code The code of the achievement. (required)
     * @return ApiResponse&lt;AchievementResponseSchema&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successfully fetched achievement. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> achievement not found. </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<AchievementResponseSchema> getAchievementAchievementsCodeGetWithHttpInfo(String code) throws ApiException {
        okhttp3.Call localVarCall = getAchievementAchievementsCodeGetValidateBeforeCall(code, null);
        Type localVarReturnType = new TypeToken<AchievementResponseSchema>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Get Achievement (asynchronously)
     * Retrieve the details of a achievement.
     * @param code The code of the achievement. (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successfully fetched achievement. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> achievement not found. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getAchievementAchievementsCodeGetAsync(String code, final ApiCallback<AchievementResponseSchema> _callback) throws ApiException {

        okhttp3.Call localVarCall = getAchievementAchievementsCodeGetValidateBeforeCall(code, _callback);
        Type localVarReturnType = new TypeToken<AchievementResponseSchema>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for getAllAchievementsAchievementsGet
     * @param type Type of achievements. (optional)
     * @param page Page number (optional, default to 1)
     * @param size Page size (optional, default to 50)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successfully fetched achievements. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getAllAchievementsAchievementsGetCall(AchievementType type, Integer page, Integer size, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/achievements";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (type != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("type", type));
        }

        if (page != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("page", page));
        }

        if (size != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("size", size));
        }

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getAllAchievementsAchievementsGetValidateBeforeCall(AchievementType type, Integer page, Integer size, final ApiCallback _callback) throws ApiException {
        return getAllAchievementsAchievementsGetCall(type, page, size, _callback);

    }

    /**
     * Get All Achievements
     * List of all achievements.
     * @param type Type of achievements. (optional)
     * @param page Page number (optional, default to 1)
     * @param size Page size (optional, default to 50)
     * @return DataPageAchievementSchema
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successfully fetched achievements. </td><td>  -  </td></tr>
     </table>
     */
    public DataPageAchievementSchema getAllAchievementsAchievementsGet(AchievementType type, Integer page, Integer size) throws ApiException {
        ApiResponse<DataPageAchievementSchema> localVarResp = getAllAchievementsAchievementsGetWithHttpInfo(type, page, size);
        return localVarResp.getData();
    }

    /**
     * Get All Achievements
     * List of all achievements.
     * @param type Type of achievements. (optional)
     * @param page Page number (optional, default to 1)
     * @param size Page size (optional, default to 50)
     * @return ApiResponse&lt;DataPageAchievementSchema&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successfully fetched achievements. </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<DataPageAchievementSchema> getAllAchievementsAchievementsGetWithHttpInfo(AchievementType type, Integer page, Integer size) throws ApiException {
        okhttp3.Call localVarCall = getAllAchievementsAchievementsGetValidateBeforeCall(type, page, size, null);
        Type localVarReturnType = new TypeToken<DataPageAchievementSchema>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Get All Achievements (asynchronously)
     * List of all achievements.
     * @param type Type of achievements. (optional)
     * @param page Page number (optional, default to 1)
     * @param size Page size (optional, default to 50)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successfully fetched achievements. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getAllAchievementsAchievementsGetAsync(AchievementType type, Integer page, Integer size, final ApiCallback<DataPageAchievementSchema> _callback) throws ApiException {

        okhttp3.Call localVarCall = getAllAchievementsAchievementsGetValidateBeforeCall(type, page, size, _callback);
        Type localVarReturnType = new TypeToken<DataPageAchievementSchema>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
}
