/*
 * Artifacts API
 *  Artifacts is an API-based MMO game where you can manage 5 characters to explore, fight, gather resources, craft items and much more.  Website: https://artifactsmmo.com/  Documentation: https://docs.artifactsmmo.com/  OpenAPI Spec: https://api.artifactsmmo.com/openapi.json 
 *
 * The version of the OpenAPI document: 3.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiCallback;
import org.openapitools.client.ApiClient;
import org.openapitools.client.ApiException;
import org.openapitools.client.ApiResponse;
import org.openapitools.client.Configuration;
import org.openapitools.client.Pair;
import org.openapitools.client.ProgressRequestBody;
import org.openapitools.client.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import org.openapitools.client.model.DataPageGEOrderSchema;
import org.openapitools.client.model.DataPageGeOrderHistorySchema;
import org.openapitools.client.model.GEOrderReponseSchema;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class GrandExchangeApi {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public GrandExchangeApi() {
        this(Configuration.getDefaultApiClient());
    }

    public GrandExchangeApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    /**
     * Build call for getGeSellHistoryGrandexchangeHistoryCodeGet
     * @param code The code of the item. (required)
     * @param seller The seller (account name) of the item. (optional)
     * @param buyer The buyer (account name) of the item. (optional)
     * @param page Page number (optional, default to 1)
     * @param size Page size (optional, default to 50)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successfully fetched orders history. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Item not found. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getGeSellHistoryGrandexchangeHistoryCodeGetCall(String code, String seller, String buyer, Integer page, Integer size, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/grandexchange/history/{code}"
            .replace("{" + "code" + "}", localVarApiClient.escapeString(code.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (seller != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("seller", seller));
        }

        if (buyer != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("buyer", buyer));
        }

        if (page != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("page", page));
        }

        if (size != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("size", size));
        }

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getGeSellHistoryGrandexchangeHistoryCodeGetValidateBeforeCall(String code, String seller, String buyer, Integer page, Integer size, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'code' is set
        if (code == null) {
            throw new ApiException("Missing the required parameter 'code' when calling getGeSellHistoryGrandexchangeHistoryCodeGet(Async)");
        }

        return getGeSellHistoryGrandexchangeHistoryCodeGetCall(code, seller, buyer, page, size, _callback);

    }

    /**
     * Get Ge Sell History
     * Fetch the sales history of the item for the last 7 days.
     * @param code The code of the item. (required)
     * @param seller The seller (account name) of the item. (optional)
     * @param buyer The buyer (account name) of the item. (optional)
     * @param page Page number (optional, default to 1)
     * @param size Page size (optional, default to 50)
     * @return DataPageGeOrderHistorySchema
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successfully fetched orders history. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Item not found. </td><td>  -  </td></tr>
     </table>
     */
    public DataPageGeOrderHistorySchema getGeSellHistoryGrandexchangeHistoryCodeGet(String code, String seller, String buyer, Integer page, Integer size) throws ApiException {
        ApiResponse<DataPageGeOrderHistorySchema> localVarResp = getGeSellHistoryGrandexchangeHistoryCodeGetWithHttpInfo(code, seller, buyer, page, size);
        return localVarResp.getData();
    }

    /**
     * Get Ge Sell History
     * Fetch the sales history of the item for the last 7 days.
     * @param code The code of the item. (required)
     * @param seller The seller (account name) of the item. (optional)
     * @param buyer The buyer (account name) of the item. (optional)
     * @param page Page number (optional, default to 1)
     * @param size Page size (optional, default to 50)
     * @return ApiResponse&lt;DataPageGeOrderHistorySchema&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successfully fetched orders history. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Item not found. </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<DataPageGeOrderHistorySchema> getGeSellHistoryGrandexchangeHistoryCodeGetWithHttpInfo(String code, String seller, String buyer, Integer page, Integer size) throws ApiException {
        okhttp3.Call localVarCall = getGeSellHistoryGrandexchangeHistoryCodeGetValidateBeforeCall(code, seller, buyer, page, size, null);
        Type localVarReturnType = new TypeToken<DataPageGeOrderHistorySchema>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Get Ge Sell History (asynchronously)
     * Fetch the sales history of the item for the last 7 days.
     * @param code The code of the item. (required)
     * @param seller The seller (account name) of the item. (optional)
     * @param buyer The buyer (account name) of the item. (optional)
     * @param page Page number (optional, default to 1)
     * @param size Page size (optional, default to 50)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successfully fetched orders history. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Item not found. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getGeSellHistoryGrandexchangeHistoryCodeGetAsync(String code, String seller, String buyer, Integer page, Integer size, final ApiCallback<DataPageGeOrderHistorySchema> _callback) throws ApiException {

        okhttp3.Call localVarCall = getGeSellHistoryGrandexchangeHistoryCodeGetValidateBeforeCall(code, seller, buyer, page, size, _callback);
        Type localVarReturnType = new TypeToken<DataPageGeOrderHistorySchema>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for getGeSellOrderGrandexchangeOrdersIdGet
     * @param id The id of the order. (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successfully fetched order. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Order not found. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getGeSellOrderGrandexchangeOrdersIdGetCall(String id, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/grandexchange/orders/{id}"
            .replace("{" + "id" + "}", localVarApiClient.escapeString(id.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getGeSellOrderGrandexchangeOrdersIdGetValidateBeforeCall(String id, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'id' is set
        if (id == null) {
            throw new ApiException("Missing the required parameter 'id' when calling getGeSellOrderGrandexchangeOrdersIdGet(Async)");
        }

        return getGeSellOrderGrandexchangeOrdersIdGetCall(id, _callback);

    }

    /**
     * Get Ge Sell Order
     * Retrieve the sell order of a item.
     * @param id The id of the order. (required)
     * @return GEOrderReponseSchema
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successfully fetched order. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Order not found. </td><td>  -  </td></tr>
     </table>
     */
    public GEOrderReponseSchema getGeSellOrderGrandexchangeOrdersIdGet(String id) throws ApiException {
        ApiResponse<GEOrderReponseSchema> localVarResp = getGeSellOrderGrandexchangeOrdersIdGetWithHttpInfo(id);
        return localVarResp.getData();
    }

    /**
     * Get Ge Sell Order
     * Retrieve the sell order of a item.
     * @param id The id of the order. (required)
     * @return ApiResponse&lt;GEOrderReponseSchema&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successfully fetched order. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Order not found. </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<GEOrderReponseSchema> getGeSellOrderGrandexchangeOrdersIdGetWithHttpInfo(String id) throws ApiException {
        okhttp3.Call localVarCall = getGeSellOrderGrandexchangeOrdersIdGetValidateBeforeCall(id, null);
        Type localVarReturnType = new TypeToken<GEOrderReponseSchema>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Get Ge Sell Order (asynchronously)
     * Retrieve the sell order of a item.
     * @param id The id of the order. (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successfully fetched order. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Order not found. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getGeSellOrderGrandexchangeOrdersIdGetAsync(String id, final ApiCallback<GEOrderReponseSchema> _callback) throws ApiException {

        okhttp3.Call localVarCall = getGeSellOrderGrandexchangeOrdersIdGetValidateBeforeCall(id, _callback);
        Type localVarReturnType = new TypeToken<GEOrderReponseSchema>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for getGeSellOrdersGrandexchangeOrdersGet
     * @param code The code of the item. (optional)
     * @param seller The seller (account name) of the item. (optional)
     * @param page Page number (optional, default to 1)
     * @param size Page size (optional, default to 50)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successfully fetched orders details. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getGeSellOrdersGrandexchangeOrdersGetCall(String code, String seller, Integer page, Integer size, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/grandexchange/orders";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (code != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("code", code));
        }

        if (seller != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("seller", seller));
        }

        if (page != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("page", page));
        }

        if (size != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("size", size));
        }

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getGeSellOrdersGrandexchangeOrdersGetValidateBeforeCall(String code, String seller, Integer page, Integer size, final ApiCallback _callback) throws ApiException {
        return getGeSellOrdersGrandexchangeOrdersGetCall(code, seller, page, size, _callback);

    }

    /**
     * Get Ge Sell Orders
     * Fetch all sell orders.
     * @param code The code of the item. (optional)
     * @param seller The seller (account name) of the item. (optional)
     * @param page Page number (optional, default to 1)
     * @param size Page size (optional, default to 50)
     * @return DataPageGEOrderSchema
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successfully fetched orders details. </td><td>  -  </td></tr>
     </table>
     */
    public DataPageGEOrderSchema getGeSellOrdersGrandexchangeOrdersGet(String code, String seller, Integer page, Integer size) throws ApiException {
        ApiResponse<DataPageGEOrderSchema> localVarResp = getGeSellOrdersGrandexchangeOrdersGetWithHttpInfo(code, seller, page, size);
        return localVarResp.getData();
    }

    /**
     * Get Ge Sell Orders
     * Fetch all sell orders.
     * @param code The code of the item. (optional)
     * @param seller The seller (account name) of the item. (optional)
     * @param page Page number (optional, default to 1)
     * @param size Page size (optional, default to 50)
     * @return ApiResponse&lt;DataPageGEOrderSchema&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successfully fetched orders details. </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<DataPageGEOrderSchema> getGeSellOrdersGrandexchangeOrdersGetWithHttpInfo(String code, String seller, Integer page, Integer size) throws ApiException {
        okhttp3.Call localVarCall = getGeSellOrdersGrandexchangeOrdersGetValidateBeforeCall(code, seller, page, size, null);
        Type localVarReturnType = new TypeToken<DataPageGEOrderSchema>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Get Ge Sell Orders (asynchronously)
     * Fetch all sell orders.
     * @param code The code of the item. (optional)
     * @param seller The seller (account name) of the item. (optional)
     * @param page Page number (optional, default to 1)
     * @param size Page size (optional, default to 50)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successfully fetched orders details. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getGeSellOrdersGrandexchangeOrdersGetAsync(String code, String seller, Integer page, Integer size, final ApiCallback<DataPageGEOrderSchema> _callback) throws ApiException {

        okhttp3.Call localVarCall = getGeSellOrdersGrandexchangeOrdersGetValidateBeforeCall(code, seller, page, size, _callback);
        Type localVarReturnType = new TypeToken<DataPageGEOrderSchema>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
}
