/*
 * Artifacts API
 *  Artifacts is an API-based MMO game where you can manage 5 characters to explore, fight, gather resources, craft items and much more.  Website: https://artifactsmmo.com/  Documentation: https://docs.artifactsmmo.com/  OpenAPI Spec: https://api.artifactsmmo.com/openapi.json 
 *
 * The version of the OpenAPI document: 3.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiCallback;
import org.openapitools.client.ApiClient;
import org.openapitools.client.ApiException;
import org.openapitools.client.ApiResponse;
import org.openapitools.client.Configuration;
import org.openapitools.client.Pair;
import org.openapitools.client.ProgressRequestBody;
import org.openapitools.client.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import org.openapitools.client.model.DataPageDropRateSchema;
import org.openapitools.client.model.DataPageTaskFullSchema;
import org.openapitools.client.model.RewardResponseSchema;
import org.openapitools.client.model.Skill;
import org.openapitools.client.model.TaskFullResponseSchema;
import org.openapitools.client.model.TaskType;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class TasksApi {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public TasksApi() {
        this(Configuration.getDefaultApiClient());
    }

    public TasksApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    /**
     * Build call for getAllTasksRewardsTasksRewardsGet
     * @param page Page number (optional, default to 1)
     * @param size Page size (optional, default to 50)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successfully fetched tasks rewards details. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getAllTasksRewardsTasksRewardsGetCall(Integer page, Integer size, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/tasks/rewards";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (page != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("page", page));
        }

        if (size != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("size", size));
        }

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getAllTasksRewardsTasksRewardsGetValidateBeforeCall(Integer page, Integer size, final ApiCallback _callback) throws ApiException {
        return getAllTasksRewardsTasksRewardsGetCall(page, size, _callback);

    }

    /**
     * Get All Tasks Rewards
     * Fetch the list of all tasks rewards. To obtain these rewards, you must exchange 6 task coins with a tasks master.
     * @param page Page number (optional, default to 1)
     * @param size Page size (optional, default to 50)
     * @return DataPageDropRateSchema
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successfully fetched tasks rewards details. </td><td>  -  </td></tr>
     </table>
     */
    public DataPageDropRateSchema getAllTasksRewardsTasksRewardsGet(Integer page, Integer size) throws ApiException {
        ApiResponse<DataPageDropRateSchema> localVarResp = getAllTasksRewardsTasksRewardsGetWithHttpInfo(page, size);
        return localVarResp.getData();
    }

    /**
     * Get All Tasks Rewards
     * Fetch the list of all tasks rewards. To obtain these rewards, you must exchange 6 task coins with a tasks master.
     * @param page Page number (optional, default to 1)
     * @param size Page size (optional, default to 50)
     * @return ApiResponse&lt;DataPageDropRateSchema&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successfully fetched tasks rewards details. </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<DataPageDropRateSchema> getAllTasksRewardsTasksRewardsGetWithHttpInfo(Integer page, Integer size) throws ApiException {
        okhttp3.Call localVarCall = getAllTasksRewardsTasksRewardsGetValidateBeforeCall(page, size, null);
        Type localVarReturnType = new TypeToken<DataPageDropRateSchema>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Get All Tasks Rewards (asynchronously)
     * Fetch the list of all tasks rewards. To obtain these rewards, you must exchange 6 task coins with a tasks master.
     * @param page Page number (optional, default to 1)
     * @param size Page size (optional, default to 50)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successfully fetched tasks rewards details. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getAllTasksRewardsTasksRewardsGetAsync(Integer page, Integer size, final ApiCallback<DataPageDropRateSchema> _callback) throws ApiException {

        okhttp3.Call localVarCall = getAllTasksRewardsTasksRewardsGetValidateBeforeCall(page, size, _callback);
        Type localVarReturnType = new TypeToken<DataPageDropRateSchema>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for getAllTasksTasksListGet
     * @param minLevel Minimum level. (optional)
     * @param maxLevel Maximum level. (optional)
     * @param skill The code of the skill. (optional)
     * @param type The type of tasks. (optional)
     * @param page Page number (optional, default to 1)
     * @param size Page size (optional, default to 50)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successfully fetched tasks details. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getAllTasksTasksListGetCall(Integer minLevel, Integer maxLevel, Skill skill, TaskType type, Integer page, Integer size, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/tasks/list";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (minLevel != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("min_level", minLevel));
        }

        if (maxLevel != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("max_level", maxLevel));
        }

        if (skill != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("skill", skill));
        }

        if (type != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("type", type));
        }

        if (page != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("page", page));
        }

        if (size != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("size", size));
        }

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getAllTasksTasksListGetValidateBeforeCall(Integer minLevel, Integer maxLevel, Skill skill, TaskType type, Integer page, Integer size, final ApiCallback _callback) throws ApiException {
        return getAllTasksTasksListGetCall(minLevel, maxLevel, skill, type, page, size, _callback);

    }

    /**
     * Get All Tasks
     * Fetch the list of all tasks.
     * @param minLevel Minimum level. (optional)
     * @param maxLevel Maximum level. (optional)
     * @param skill The code of the skill. (optional)
     * @param type The type of tasks. (optional)
     * @param page Page number (optional, default to 1)
     * @param size Page size (optional, default to 50)
     * @return DataPageTaskFullSchema
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successfully fetched tasks details. </td><td>  -  </td></tr>
     </table>
     */
    public DataPageTaskFullSchema getAllTasksTasksListGet(Integer minLevel, Integer maxLevel, Skill skill, TaskType type, Integer page, Integer size) throws ApiException {
        ApiResponse<DataPageTaskFullSchema> localVarResp = getAllTasksTasksListGetWithHttpInfo(minLevel, maxLevel, skill, type, page, size);
        return localVarResp.getData();
    }

    /**
     * Get All Tasks
     * Fetch the list of all tasks.
     * @param minLevel Minimum level. (optional)
     * @param maxLevel Maximum level. (optional)
     * @param skill The code of the skill. (optional)
     * @param type The type of tasks. (optional)
     * @param page Page number (optional, default to 1)
     * @param size Page size (optional, default to 50)
     * @return ApiResponse&lt;DataPageTaskFullSchema&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successfully fetched tasks details. </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<DataPageTaskFullSchema> getAllTasksTasksListGetWithHttpInfo(Integer minLevel, Integer maxLevel, Skill skill, TaskType type, Integer page, Integer size) throws ApiException {
        okhttp3.Call localVarCall = getAllTasksTasksListGetValidateBeforeCall(minLevel, maxLevel, skill, type, page, size, null);
        Type localVarReturnType = new TypeToken<DataPageTaskFullSchema>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Get All Tasks (asynchronously)
     * Fetch the list of all tasks.
     * @param minLevel Minimum level. (optional)
     * @param maxLevel Maximum level. (optional)
     * @param skill The code of the skill. (optional)
     * @param type The type of tasks. (optional)
     * @param page Page number (optional, default to 1)
     * @param size Page size (optional, default to 50)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successfully fetched tasks details. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getAllTasksTasksListGetAsync(Integer minLevel, Integer maxLevel, Skill skill, TaskType type, Integer page, Integer size, final ApiCallback<DataPageTaskFullSchema> _callback) throws ApiException {

        okhttp3.Call localVarCall = getAllTasksTasksListGetValidateBeforeCall(minLevel, maxLevel, skill, type, page, size, _callback);
        Type localVarReturnType = new TypeToken<DataPageTaskFullSchema>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for getTaskTasksListCodeGet
     * @param code The code of the task. (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successfully fetched task. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Task not found. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getTaskTasksListCodeGetCall(String code, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/tasks/list/{code}"
            .replace("{" + "code" + "}", localVarApiClient.escapeString(code.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getTaskTasksListCodeGetValidateBeforeCall(String code, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'code' is set
        if (code == null) {
            throw new ApiException("Missing the required parameter 'code' when calling getTaskTasksListCodeGet(Async)");
        }

        return getTaskTasksListCodeGetCall(code, _callback);

    }

    /**
     * Get Task
     * Retrieve the details of a task.
     * @param code The code of the task. (required)
     * @return TaskFullResponseSchema
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successfully fetched task. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Task not found. </td><td>  -  </td></tr>
     </table>
     */
    public TaskFullResponseSchema getTaskTasksListCodeGet(String code) throws ApiException {
        ApiResponse<TaskFullResponseSchema> localVarResp = getTaskTasksListCodeGetWithHttpInfo(code);
        return localVarResp.getData();
    }

    /**
     * Get Task
     * Retrieve the details of a task.
     * @param code The code of the task. (required)
     * @return ApiResponse&lt;TaskFullResponseSchema&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successfully fetched task. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Task not found. </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<TaskFullResponseSchema> getTaskTasksListCodeGetWithHttpInfo(String code) throws ApiException {
        okhttp3.Call localVarCall = getTaskTasksListCodeGetValidateBeforeCall(code, null);
        Type localVarReturnType = new TypeToken<TaskFullResponseSchema>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Get Task (asynchronously)
     * Retrieve the details of a task.
     * @param code The code of the task. (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successfully fetched task. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Task not found. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getTaskTasksListCodeGetAsync(String code, final ApiCallback<TaskFullResponseSchema> _callback) throws ApiException {

        okhttp3.Call localVarCall = getTaskTasksListCodeGetValidateBeforeCall(code, _callback);
        Type localVarReturnType = new TypeToken<TaskFullResponseSchema>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for getTasksRewardTasksRewardsCodeGet
     * @param code The code of the tasks reward. (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successfully fetched tasks reward. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Tasks reward not found. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getTasksRewardTasksRewardsCodeGetCall(String code, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/tasks/rewards/{code}"
            .replace("{" + "code" + "}", localVarApiClient.escapeString(code.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getTasksRewardTasksRewardsCodeGetValidateBeforeCall(String code, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'code' is set
        if (code == null) {
            throw new ApiException("Missing the required parameter 'code' when calling getTasksRewardTasksRewardsCodeGet(Async)");
        }

        return getTasksRewardTasksRewardsCodeGetCall(code, _callback);

    }

    /**
     * Get Tasks Reward
     * Retrieve the details of a tasks reward.
     * @param code The code of the tasks reward. (required)
     * @return RewardResponseSchema
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successfully fetched tasks reward. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Tasks reward not found. </td><td>  -  </td></tr>
     </table>
     */
    public RewardResponseSchema getTasksRewardTasksRewardsCodeGet(String code) throws ApiException {
        ApiResponse<RewardResponseSchema> localVarResp = getTasksRewardTasksRewardsCodeGetWithHttpInfo(code);
        return localVarResp.getData();
    }

    /**
     * Get Tasks Reward
     * Retrieve the details of a tasks reward.
     * @param code The code of the tasks reward. (required)
     * @return ApiResponse&lt;RewardResponseSchema&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successfully fetched tasks reward. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Tasks reward not found. </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<RewardResponseSchema> getTasksRewardTasksRewardsCodeGetWithHttpInfo(String code) throws ApiException {
        okhttp3.Call localVarCall = getTasksRewardTasksRewardsCodeGetValidateBeforeCall(code, null);
        Type localVarReturnType = new TypeToken<RewardResponseSchema>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Get Tasks Reward (asynchronously)
     * Retrieve the details of a tasks reward.
     * @param code The code of the tasks reward. (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successfully fetched tasks reward. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Tasks reward not found. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getTasksRewardTasksRewardsCodeGetAsync(String code, final ApiCallback<RewardResponseSchema> _callback) throws ApiException {

        okhttp3.Call localVarCall = getTasksRewardTasksRewardsCodeGetValidateBeforeCall(code, _callback);
        Type localVarReturnType = new TypeToken<RewardResponseSchema>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
}
